import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { randomUUID,createHash } from 'node:crypto';
import { PGlite } from '@electric-sql/pglite';
const sha=s=>createHash('sha256').update(s).digest('hex');
test('PostgreSQL transactions, pricing, permissions, table lifecycle and reporting',async()=>{
 const db=new PGlite();
 try {
  await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
   create schema auth; create table auth.users(id uuid primary key);
   create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
   grant usage on schema public,auth to anon,authenticated,service_role; grant execute on function auth.uid() to authenticated,service_role;`);
  for (const file of ['migrations/202610050001_initial_schema.sql','migrations/202610050002_application_api.sql','seed.sql','menu-seed.sql']) await db.exec(readFileSync(new URL('../supabase/'+file,import.meta.url),'utf8'));
  const owner=randomUUID(),admin=randomUUID();
  await db.query('insert into auth.users(id) values($1),($2)',[owner,admin]);
  await db.query("insert into public.admins(auth_user_id,account_slot,display_name,role) values($1,1,'Owner','owner'),($2,2,'Staff','admin')",[owner,admin]);
  const query=async(sql,args=[])=> (await db.query(sql,args)).rows;
  const scalar=async(sql,args=[])=>Object.values((await query(sql,args))[0])[0];
  const rpc=async(name,args=[])=>scalar(`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')})`,args);
  const catalog=await rpc('menu_catalog'); assert.equal(catalog.length,38); assert.equal(catalog.find(m=>m.code==='soft-pork-noodles').groups.length,4);
  const qr=Array.from({length:9},(_,i)=>({tableNumber:i<8?i+1:null,hash:sha('entry'+i)}));
  await rpc('rotate_qr',[owner,JSON.stringify(qr)]);
  const session=await rpc('customer_bootstrap',[qr[0].hash,sha('customer1'),null]); assert.equal(session.tableNumber,1);
  const resumed=await rpc('customer_bootstrap',[qr[0].hash,sha('unused'),sha('customer1')]); assert.equal(resumed.resumed,true); assert.equal(resumed.visitId,session.visitId);
  const line={itemCode:'soft-pork-noodles',variantCode:'normal',quantity:2,options:[{groupCode:'noodle',optionCode:'mama',quantity:1},{groupCode:'broth',optionCode:'clear',quantity:1}],notes:['ไม่ใส่ผัก']};
  const payload={lines:[line],expectedTotalSatang:11000}; const key=randomUUID(),hash=sha(JSON.stringify(payload));
  const order=await rpc('place_order',[JSON.stringify(payload),key,hash,sha('customer1'),null]); assert.equal(order.totalSatang,11000); assert.equal(order.lines[0].unitSatang,5500);
  assert.equal((await rpc('place_order',[JSON.stringify(payload),key,hash,sha('customer1'),null])).id,order.id);
  await assert.rejects(()=>rpc('place_order',[JSON.stringify(payload),key,sha('changed'),sha('customer1'),null]),/รหัสอ้างอิง/);
  await assert.rejects(()=>rpc('close_table',[owner,1]),/เคลียร์/);
  const bad={lines:[{...line,options:[]}],expectedTotalSatang:10000};
  await assert.rejects(()=>rpc('place_order',[JSON.stringify(bad),randomUUID(),sha('bad'),sha('customer1'),null]),/ตัวเลือก/);
  assert.equal(await scalar('select count(*)::integer from public.orders'),1,'Rejected order must roll back every row');
  await rpc('edit_menu',[owner,'soft-pork-noodles',JSON.stringify({normal:6000,special:7000}),true]);
  assert.equal((await rpc('order_json',[order.id])).totalSatang,11000,'Snapshot does not change');
  await assert.rejects(()=>rpc('place_order',[JSON.stringify(payload),randomUUID(),hash,sha('customer1'),null]),/ราคาเปลี่ยน/);
  await assert.rejects(()=>rpc('edit_menu',[admin,'water',JSON.stringify({normal:1000}),true]),/สิทธิ์/);
  await assert.rejects(()=>rpc('staff_order_action',[admin,order.id,'preparing',null]),/คำสั่ง/);
  for (const status of ['preparing','ready','served']) await rpc('staff_order_action',[admin,order.id,'status',status]);
  await rpc('staff_order_action',[admin,order.id,'pay','cash']); await rpc('staff_order_action',[admin,order.id,'pay','cash']);
  assert.equal(await scalar("select count(*)::integer from public.payment_transactions where kind='capture'"),1);
  const today=await scalar("select (now() at time zone 'Asia/Bangkok')::date::text");
  const summaries=[{date:today,channel:'grabfood',grossSatang:150000,discountSatang:10000,refundSatang:5000,orderCount:10}];
  const importKey=randomUUID();
  await rpc('import_delivery_summary',[owner,JSON.stringify(summaries),sha('file'),importKey]);
  await rpc('import_delivery_summary',[owner,JSON.stringify(summaries),sha('file'),importKey]);
  assert.equal(await scalar('select count(*)::integer from public.delivery_daily_sales'),1);
  await rpc('import_delivery_summary',[owner,JSON.stringify([{...summaries[0],grossSatang:160000}]),sha('edit'),randomUUID()]);
  await rpc('import_delivery_summary',[owner,JSON.stringify(summaries),sha('file'),randomUUID()]);
  assert.equal(await scalar('select gross_satang::integer from public.delivery_daily_sales'),150000,'Owner can intentionally restore a previous summary');
  await assert.rejects(()=>rpc('import_delivery_summary',[owner,JSON.stringify([{...summaries[0],grossSatang:190000},{...summaries[0],channel:'lineman',discountSatang:999999}]),sha('invalid-batch'),randomUUID()]));
  assert.equal(await scalar('select gross_satang::integer from public.delivery_daily_sales'),150000,'Invalid batch rolls back every channel');
  await db.query("select set_config('request.jwt.claim.sub',$1,false)",[owner]); await db.exec('set role authenticated');
  const to=await scalar('select ($1::date+1)::text',[today]);
  const report=await rpc('staff_sales_report',[today,to]); assert.equal(report.gross,151000); assert.equal(report.refund,5000); assert.equal(report.count,11); assert.equal(report.hourly.length,24); assert.equal(report.top[0].quantity,2);
  await assert.rejects(()=>db.query('select * from public.customer_sessions'),/permission denied/);
  await assert.rejects(()=>rpc('place_order',[JSON.stringify(payload),randomUUID(),hash,sha('customer1'),null]),/permission denied/);
  await assert.rejects(()=>db.query('update public.orders set gross_satang=0'),/permission denied/);
  await db.exec('reset role');
  await rpc('close_table',[admin,1]); await assert.rejects(()=>rpc('customer_orders',[sha('customer1')]),/หมดอายุ/);
  const next=await rpc('customer_bootstrap',[qr[0].hash,sha('customer2'),null]); assert.notEqual(next.visitId,session.visitId);
  await rpc('staff_order_action',[owner,order.id,'refund',null]); await rpc('staff_order_action',[owner,order.id,'refund',null]);
  assert.equal(await scalar("select count(*)::integer from public.payment_transactions where kind='refund'"),1);
  // Two customer sessions cannot see one another's order histories.
  assert.deepEqual(await rpc('customer_orders',[sha('customer2')]),[]);
  const takeaway=await rpc('customer_bootstrap',[qr[8].hash,sha('takeaway'),null]); assert.equal(takeaway.channel,'takeaway');
  const takePayload={lines:[{itemCode:'water',variantCode:'normal',quantity:1,options:[],notes:[]}],expectedTotalSatang:1000};
  const queues=await Promise.all(Array.from({length:15},(_,i)=>rpc('place_order',[JSON.stringify(takePayload),randomUUID(),sha('queue'+i),sha('takeaway'),null])));
  assert.equal(new Set(queues.map(o=>o.queueNumber)).size,15); assert.equal(queues[0].queueNumber,1);
  await db.query("select set_config('request.jwt.claim.sub',$1,false)",[randomUUID()]); await db.exec('set role authenticated');
  assert.equal(await scalar('select count(*)::integer from public.orders'),0,'No staff profile means no order access');
  await assert.rejects(()=>rpc('staff_sales_report',[today,to]),/เข้าสู่ระบบ/);
  await db.exec('reset role; set role anon'); await assert.rejects(()=>rpc('menu_catalog'),/permission denied/);
 } finally { await db.close(); }
});
