import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, readdirSync } from 'node:fs';
import { randomUUID, randomBytes, createHash } from 'node:crypto';
import { PGlite } from '@electric-sql/pglite';
const sha = value => createHash('sha256').update(value).digest('hex');
const token = () => randomBytes(32).toString('hex');

test('Ten persistent QR entries preserve printed links and only the owner can explicitly rotate one entry', async () => {
  const db = new PGlite();
  const rows = async (sql, params = []) => (await db.query(sql, params)).rows;
  const rpc = async (name, params = []) => (await rows(`select public.${name}(${params.map((_, i) => '$' + (i + 1)).join(',')}) result`, params))[0].result;
  try {
    await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
      create schema auth; create table auth.users(id uuid primary key);
      create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
      grant usage on schema public,auth to anon,authenticated,service_role;
      grant execute on function auth.uid() to authenticated,service_role;`);
    const root = new URL('../supabase/', import.meta.url);
    const files = readdirSync(new URL('migrations/', root)).filter(name => name.endsWith('.sql')).sort();
    const migration = files.find(name => name.endsWith('_persistent_ordering_qr.sql'));
    assert.ok(migration, 'A migration must replace destructive QR viewing with ten persistent entries');
    for (const file of files.slice(0, 2)) await db.exec(readFileSync(new URL('migrations/' + file, root), 'utf8'));
    for (const file of ['seed.sql', 'menu-seed.sql']) await db.exec(readFileSync(new URL(file, root), 'utf8'));
    for (const file of files.slice(2).filter(name => name !== migration)) await db.exec(readFileSync(new URL('migrations/' + file, root), 'utf8'));
    const owner = randomUUID(), admin = randomUUID();
    await db.query('insert into auth.users values($1),($2)', [owner, admin]);
    await db.query("insert into public.admins(auth_user_id,account_slot,display_name,role) values($1,1,'Owner','owner'),($2,2,'Admin','admin')", [owner, admin]);
    const legacyTokens = Array.from({ length: 9 }, token);
    await rpc('rotate_qr', [owner, JSON.stringify(legacyTokens.map((value, i) => ({ tableNumber: i < 8 ? i + 1 : null, hash: sha(value) })))]);
    const legacy = await rows('select id,kind,table_id,token_hash,is_active from public.qr_entrypoints order by id');
    await db.exec(readFileSync(new URL('migrations/' + migration, root), 'utf8'));
    assert.deepEqual(await rows('select id,kind,table_id,token_hash,is_active from public.qr_entrypoints where id=any($1::uuid[]) order by id', [legacy.map(row => row.id)]), legacy);
    await db.query("select set_config('request.jwt.claim.sub',$1,false)", [owner]);
    await db.exec('set role authenticated');
    const first = await rpc('owner_qr_entries');
    assert.equal(first.length, 10);
    assert.equal(new Set(first.map(entry => entry.token)).size, 10);
    assert.deepEqual(first.map(entry => entry.key), [...Array.from({ length: 8 }, (_, i) => 'table-' + (i + 1)), 'takeaway-front', 'takeaway-remote']);
    assert.deepEqual(await rpc('owner_qr_entries'), first, 'viewing repeatedly must not change any link');
    await assert.rejects(() => rows('select display_token from public.qr_entrypoints'), /permission denied/);
    await db.exec('reset role');
    for (const [i, old] of legacyTokens.entries()) {
      const opened = await rpc('customer_bootstrap', [sha(old), sha(token()), null]);
      assert.equal(opened.channel, i < 8 ? 'dine_in' : 'takeaway');
      assert.equal(opened.tableNumber, i < 8 ? i + 1 : null);
    }
    const remoteSession = token();
    assert.equal((await rpc('customer_bootstrap', [sha(first[9].token), sha(remoteSession), null])).channel, 'takeaway');
    const frontSession = token();
    const front = await rpc('customer_bootstrap', [sha(first[8].token), sha(frontSession), null]);
    assert.equal(front.channel, 'takeaway');
    const input = { channel: 'takeaway', lines: [{ itemCode: 'water', variantCode: 'normal', quantity: 1, options: [], notes: [] }], expectedTotalSatang: 1000, takeaway: { customerName: 'QR test', villageDelivery: false, deliveryAddress: '', deliveryPhone: '' } };
    const orderKey = randomUUID();
    const bill = await rpc('place_order', [JSON.stringify(input), orderKey, sha(JSON.stringify(input)), sha(frontSession), null]);
    const sessionsBefore = await rows('select * from public.customer_sessions order by id');
    const visitsBefore = await rows('select * from public.table_sessions order by id');
    await db.exec('set role authenticated');
    const rotateKey = randomUUID();
    const rotated = await rpc('owner_rotate_qr', ['takeaway-front', first[8].revision, rotateKey]);
    assert.notEqual(rotated.token, first[8].token);
    assert.equal(rotated.revision, first[8].revision + 1);
    assert.deepEqual(await rpc('owner_rotate_qr', ['takeaway-front', first[8].revision, rotateKey]), rotated, 'lost-response retry must return the same replacement');
    await assert.rejects(() => rpc('owner_rotate_qr', ['takeaway-front', first[8].revision, randomUUID()]), error => error.code === 'PT409');
    const after = await rpc('owner_qr_entries');
    assert.deepEqual(after.filter(entry => entry.key !== 'takeaway-front'), first.filter(entry => entry.key !== 'takeaway-front'));
    await db.exec('reset role');
    for (const invalid of [legacyTokens[8], first[8].token]) await assert.rejects(() => rpc('customer_bootstrap', [sha(invalid), sha(token()), null]), error => error.code === 'PT400');
    assert.deepEqual(await rows('select * from public.customer_sessions order by id'), sessionsBefore);
    assert.deepEqual(await rows('select * from public.table_sessions order by id'), visitsBefore);
    assert.deepEqual(await rpc('order_json', [bill.id]), bill);
    assert.equal((await rpc('place_order', [JSON.stringify(input), orderKey, sha(JSON.stringify(input)), sha(frontSession), null])).id, bill.id);
    assert.equal((await rpc('customer_bootstrap', [sha(rotated.token), sha(token()), null])).channel, 'takeaway');
    await db.query("select set_config('request.jwt.claim.sub',$1,false)", [admin]);
    await db.exec('set role authenticated');
    await assert.rejects(() => rpc('owner_qr_entries'), error => error.code === 'PT403');
    await assert.rejects(() => rpc('owner_rotate_qr', ['table-1', 1, randomUUID()]), error => error.code === 'PT403');
    await db.exec('reset role; set role anon');
    await assert.rejects(() => rpc('owner_qr_entries'), /permission denied/);
    await assert.rejects(() => rpc('owner_rotate_qr', ['table-1', 1, randomUUID()]), /permission denied/);
    await db.exec('reset role; set role service_role');
    await assert.rejects(() => rpc('rotate_qr', [owner, JSON.stringify(legacyTokens.map((value, i) => ({ tableNumber: i < 8 ? i + 1 : null, hash: sha(value) })))]), error => error.code === 'PT409');
  } finally { await db.close(); }
});
