import { useEffect, useRef, useState } from 'react';
import { api, mode } from '../api.ts';
import type { CustomerSession, MenuItem, Order } from '../domain.ts';
import { money, orderLabel, statusNames, thaiTime } from '../domain.ts';
import { DeliveryDetails } from './TakeawayForm.tsx';
import Ordering from './Ordering.tsx';
export default function Customer({ catalog, refreshMenu }: { catalog: MenuItem[]; refreshMenu: () => Promise<MenuItem[]> }) {
  const [entry] = useState(() => { const params = new URLSearchParams(location.search); return params.get('qr') ?? params.get('table') ?? (mode === 'demo' ? '1' : sessionStorage.getItem('prod-entry') ?? ''); });
  const [session, setSession] = useState<CustomerSession | null>(null); const [orders, setOrders] = useState<Order[]>([]); const [error, setError] = useState(''); const [statusView, setStatusView] = useState(location.hash === '#status');
  const activeOrders = useRef(false); activeOrders.current = orders.some(o => !['served', 'cancelled'].includes(o.status));
  useEffect(() => { if (!entry) return; let alive = true; const key = 'prod-session:' + entry; const old = sessionStorage.getItem(key); void api.bootstrap(entry, old ?? undefined).then(value => { if (alive) { setSession(value); sessionStorage.setItem(key, value.token); sessionStorage.setItem('prod-entry', entry); if (mode === 'supabase' && new URLSearchParams(location.search).has('qr')) history.replaceState(null, '', location.pathname + location.hash); } }).catch(e => { if (alive) setError(e.message); }); return () => { alive = false; }; }, [entry]);
  useEffect(() => { if (!session) return; let alive = true; const refresh = () => { if (!document.hidden) void api.customerOrders(session).then(value => { if (alive) { setOrders(value); setError(''); } }).catch(e => { if (alive) setError(e.message); }); }; refresh(); const timer = setInterval(() => { if (activeOrders.current) refresh(); }, 30000); document.addEventListener('visibilitychange', refresh); return () => { alive = false; clearInterval(timer); document.removeEventListener('visibilitychange', refresh); }; }, [session]);
  if (!entry) return <main className="customer-app customer-container empty-state"><span aria-hidden="true">🍜</span><h1>ยินดีต้อนรับร้านโปรด</h1><p>สแกน QR บนโต๊ะ เพื่อเลือกอาหารได้เลย</p><a className="link-button" href="/admin">เข้าสู่ระบบพนักงาน</a></main>;
  if (!session) return <main className="customer-app customer-container"><h1>{error ? 'ยังเริ่มสั่งไม่ได้' : 'กำลังเปิดเมนู…'}</h1><p role={error ? 'alert' : 'status'}>{error || 'รอสักครู่นะคะ'}</p>{error && <button onClick={() => location.reload()}>ลองอีกครั้ง</button>}</main>;
  const context = session.channel === 'dine_in' ? `โต๊ะ ${session.tableNumber} · ทานที่ร้าน` : 'สั่งกลับบ้าน · รับเลขคิวหลังสั่ง';
  const active = orders.some(o => !['served', 'cancelled'].includes(o.status));
  return <>
    {orders.length > 0 && <nav className="customer-tabs customer-app" aria-label="การสั่งอาหาร"><button aria-pressed={!statusView} className={!statusView ? 'active' : ''} onClick={() => { setStatusView(false); history.replaceState(null, '', '#menu'); }}>เลือกอาหาร</button><button aria-pressed={statusView} className={statusView ? 'active' : ''} onClick={() => { setStatusView(true); history.replaceState(null, '', '#status'); }}>ออเดอร์ของฉัน {active && <span className="small-dot" />}</button></nav>}
    {statusView ? <main className="customer-app customer-container"><div className="context-label">{context}</div><h1>ออเดอร์ของคุณ</h1><p>ร้านได้รับรายการแล้ว ดูความคืบหน้าได้ที่นี่</p>{error && <p className="error-message" role="alert">{error}</p>}{[...orders].reverse().map(order => <article className="customer-order" key={order.id}><div className="order-title"><h2>{orderLabel(order)}</h2><span>{thaiTime(order.createdAt)}</span></div><DeliveryDetails details={order.takeaway} /><span className={'status-badge status-' + order.status}>{statusNames[order.status]}</span>{order.lines.map(line => <div className="receipt-line" key={line.id}><div><strong>{line.name} × {line.quantity}</strong><p>{[line.variantName, ...line.optionNames, ...line.notes].join(' · ')}</p>{line.freeNote && <p className="kitchen-note">{line.freeNote}</p>}</div><strong>{money(line.totalSatang)}</strong></div>)}<div className="bill-total"><span>{order.refundedAt ? 'คืนเงินแล้ว' : order.paidAt ? 'ชำระเงินแล้ว' : 'ชำระที่แคชเชียร์'}</span><strong>{money(order.totalSatang)}</strong></div></article>)}<button className="primary-action" onClick={() => setStatusView(false)}>เลือกอาหารเพิ่ม</button></main> : <Ordering isTakeaway={session.channel === 'takeaway'} key={entry} catalog={catalog} context={context} storageKey={'prod-cart:' + entry + ':' + session.visitId} onRefresh={refreshMenu} onSubmit={(lines, total, key, takeaway) => api.createOrder(session, lines, total, key, takeaway)} onSubmitted={order => { setOrders(previous => previous.some(o => o.id === order.id) ? previous : [...previous, order]); setStatusView(true); history.replaceState(null, '', '#status'); }} />}
  </>;
}
