import { useCallback, useEffect, useRef, useState } from 'react';
import QRCode from 'qrcode';
import { api, mode } from '../api.ts';
import type { StaffState } from '../api.ts';
import type { DeliverySummary, MenuItem, Order, Staff as Identity, Status } from '../domain.ts';
import { businessDate, canTransition, channelNames, money, orderLabel, parseBaht, statusNames, thaiTime, validateSummary } from '../domain.ts';
import Ordering from './Ordering.tsx';
import Dashboard from './Dashboard.tsx';
type Tab = 'pos' | 'kitchen' | 'dashboard' | 'delivery' | 'menu' | 'qr' | 'accounts';
const tabs: [Tab, string][] = [['pos', 'โต๊ะ / POS'], ['kitchen', 'ห้องครัว'], ['dashboard', 'ยอดขาย'], ['delivery', 'Delivery'], ['menu', 'จัดการเมนู'], ['qr', 'QR โต๊ะ'], ['accounts', 'บัญชีร้าน']];
const emptyState: StaffState = { orders: [], visits: {}, summaries: [] };
function Ticket({ order, identity, busy, onAction }: { order: Order; identity: Identity; busy: boolean; onAction: (order: Order, action: string, value?: string) => void }) {
  const next: Partial<Record<Status, Status>> = { new: 'preparing', preparing: 'ready', ready: 'served' }; const target = next[order.status];
  return <article className={'ticket status-border-' + order.status}><div className="ticket-top"><div><h2>{orderLabel(order)}</h2><span className="muted">#{order.id.slice(0, 6).toUpperCase()} · {thaiTime(order.createdAt)}</span></div><span className={'status-badge status-' + order.status}>{statusNames[order.status]}</span></div><div className="ticket-lines">{order.lines.map(line => <div key={line.id}><div><strong>{line.quantity} × {line.name}</strong><span>{money(line.totalSatang)}</span></div><p>{[line.variantName, ...line.optionNames, ...line.notes].join(' · ')}</p></div>)}</div><div className="ticket-total"><span>{order.refundedAt ? 'คืนเงินแล้ว' : order.paidAt ? '✓ ชำระแล้ว' : 'ยังไม่ชำระ'}</span><strong>{money(order.totalSatang)}</strong></div><div className="ticket-actions">{target && <button className="primary-action" disabled={busy} onClick={() => onAction(order, 'status', target)}>{statusNames[target]}</button>}{!order.paidAt && order.status !== 'cancelled' && <button disabled={busy} onClick={() => onAction(order, 'payment')}>รับชำระเงิน</button>}{canTransition(order.status, 'cancelled') && <button className="danger-text" disabled={busy} onClick={() => onAction(order, 'status', 'cancelled')}>ยกเลิก</button>}{identity.role === 'owner' && order.paidAt && !order.refundedAt && <button className="danger-text" disabled={busy} onClick={() => onAction(order, 'refund')}>คืนเงินเต็มจำนวน</button>}</div></article>;
}
export default function Staff({ catalog, refreshMenu }: { catalog: MenuItem[]; refreshMenu: () => Promise<MenuItem[]> }) {
  const [identity, setIdentity] = useState<Identity | null>(null); const [restoring, setRestoring] = useState(true); const [account, setAccount] = useState(mode === 'demo' ? 'demo-1' : ''); const [password, setPassword] = useState('');
  const [state, setState] = useState<StaffState>(emptyState); const [tab, setTab] = useState<Tab>('pos'); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false); const [filter, setFilter] = useState('all');
  const [compose, setCompose] = useState<{ channel: 'dine_in' | 'takeaway'; table: number | null } | null>(null); const [payment, setPayment] = useState<Order | null>(null); const [sound, setSound] = useState(false);
  const known = useRef<Set<string> | null>(null); const audio = useRef<AudioContext | null>(null); const soundRef = useRef(false); const loadInFlight = useRef(false); const loadAgain = useRef(false);
  const refresh = useCallback(async (changed?: Order) => {
    if (!identity) return;
    if (changed) { setState(previous => ({ ...previous, orders: [...previous.orders.filter(o => o.id !== changed.id), changed] })); return; }
    if (loadInFlight.current) { loadAgain.current = true; return; } loadInFlight.current = true;
    try { const value = await api.state(identity); setState(value); } catch (e) { setError((e as Error).message); } finally { loadInFlight.current = false; if (loadAgain.current) { loadAgain.current = false; void refresh(); } }
  }, [identity]);
  useEffect(() => { let alive = true; void api.restoreStaff().then(value => { if (alive) setIdentity(value); }).finally(() => { if (alive) setRestoring(false); }); return () => { alive = false; }; }, []);
  useEffect(() => { if (!identity) return; known.current = null; void refresh(); const stop = api.watch(identity, changed => { void refresh(changed); }); const visible = () => { if (!document.hidden) void refresh(); }; document.addEventListener('visibilitychange', visible); return () => { stop(); document.removeEventListener('visibilitychange', visible); }; }, [identity, refresh]);
  useEffect(() => { const ids = new Set(state.orders.map(o => o.id)); if (known.current && [...ids].some(id => !known.current!.has(id)) && soundRef.current && audio.current) { const oscillator = audio.current.createOscillator(); const gain = audio.current.createGain(); oscillator.connect(gain); gain.connect(audio.current.destination); oscillator.frequency.value = 660; gain.gain.value = 0.15; oscillator.start(); oscillator.stop(audio.current.currentTime + 0.35); } known.current = ids; }, [state.orders]);
  async function login() { setBusy(true); setError(''); try { setIdentity(await api.login(account, password)); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function action(order: Order, kind: string, value?: string) {
    if (kind === 'payment') { setPayment(order); return; }
    if ((kind === 'refund' || value === 'cancelled') && !confirm(kind === 'refund' ? `คืนเงิน ${money(order.totalSatang)} สำหรับ ${orderLabel(order)} ใช่ไหม?` : `ยกเลิกออเดอร์ ${orderLabel(order)} ใช่ไหม?`)) return;
    setBusy(true); setError(''); try { if (kind === 'status') await api.status(identity!, order.id, value as Status); else if (kind === 'refund') await api.refund(identity!, order.id); else await api.pay(identity!, order.id, value!); setPayment(null); setNotice('บันทึกแล้ว'); await refresh(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  async function closeTable(table: number) { if (!confirm(`ปิดรอบโต๊ะ ${table} และเริ่มรอบใหม่สำหรับลูกค้ากลุ่มถัดไป?`)) return; setBusy(true); try { await api.close(identity!, table); await refresh(); setNotice(`ปิดโต๊ะ ${table} แล้ว`); setError(''); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  if (restoring) return <main className="staff-container"><p role="status">กำลังตรวจบัญชี…</p></main>;
  if (!identity) return <main className="login-screen"><div className="login-card"><span className="login-emoji" aria-hidden="true">🍜</span><p className="eyebrow">โปรด · หลังร้าน</p><h1>เข้าสู่ระบบร้าน</h1><p className="muted">จัดการโต๊ะ ห้องครัว และยอดขาย</p><form onSubmit={e => { e.preventDefault(); void login(); }}><label>{mode === 'demo' ? 'บัญชีทดลอง' : 'อีเมลพนักงาน'}{mode === 'demo' ? <select value={account} onChange={e => setAccount(e.target.value)}><option value="demo-1">เจ้าของร้าน</option>{[2, 3, 4].map(n => <option key={n} value={'demo-' + n}>พนักงาน {n - 1}</option>)}</select> : <input type="email" autoComplete="username" value={account} onChange={e => setAccount(e.target.value)} required />}</label><label>{mode === 'demo' ? 'รหัสทดลอง: 1234' : 'รหัสผ่าน'}<input type="password" autoComplete="current-password" value={password} onChange={e => setPassword(e.target.value)} required /></label>{error && <p className="error-message" role="alert">{error}</p>}<button className="primary-action" disabled={busy}>{busy ? 'กำลังเข้าสู่ระบบ…' : 'เข้าสู่ระบบ'}</button></form><a href="/?table=1">← กลับหน้าสั่งอาหาร</a></div></main>;
  if (compose) return <Ordering catalog={catalog} context={compose.table ? `POS · โต๊ะ ${compose.table}` : 'POS · สั่งกลับบ้าน'} storageKey={'prod-pos-cart:' + identity.id + ':' + compose.table} onRefresh={refreshMenu} onExit={() => setCompose(null)} onSubmit={(lines, total, key) => api.posOrder(identity, lines, total, compose.channel, compose.table, key)} onSubmitted={order => { setCompose(null); setFilter(order.tableNumber ? String(order.tableNumber) : 'takeaway'); setNotice('เปิดออเดอร์ ' + orderLabel(order) + ' แล้ว'); void refresh(); }} />;
  if (payment) return <main className="staff-container payment-screen"><button onClick={() => setPayment(null)}>← กลับไปออเดอร์</button><h1>รับชำระเงิน · {orderLabel(payment)}</h1><div className="panel">{payment.lines.map(l => <div className="receipt-line" key={l.id}><span>{l.quantity} × {l.name}</span><strong>{money(l.totalSatang)}</strong></div>)}<div className="bill-total"><span>ยอดที่ต้องชำระ</span><strong>{money(payment.totalSatang)}</strong></div><p className="info-message">บันทึกหลังแคชเชียร์รับเงินหรือตรวจรายการโอนแล้ว</p><div className="payment-methods"><button className="primary-action" disabled={busy} onClick={() => void action(payment, 'pay', 'cash')}>รับเงินสดแล้ว</button><button disabled={busy} onClick={() => void action(payment, 'pay', 'promptpay')}>ตรวจยอด PromptPay แล้ว</button></div>{error && <p role="alert" className="error-message">{error}</p>}</div></main>;
  const activeOrders = state.orders.filter(o => !['served', 'cancelled'].includes(o.status));
  const visibleOrders = state.orders.filter(o => filter === 'all' ? (o.status !== 'cancelled' && (!o.paidAt || o.status !== 'served' || Boolean(o.visitId && state.visits[o.tableNumber!]?.id === o.visitId))) : filter === 'takeaway' ? o.channel === 'takeaway' && (o.status !== 'served' || !o.paidAt) && o.status !== 'cancelled' : o.tableNumber === Number(filter) && o.visitId === state.visits[filter]?.id);
  return <div className="staff-app"><header className="staff-topbar"><div><strong>โปรด <span>หลังร้าน</span></strong><p>{identity.name} · {identity.role === 'owner' ? 'เจ้าของร้าน' : 'พนักงาน'}</p></div><div><button onClick={async () => { if (!audio.current) audio.current = new AudioContext(); await audio.current.resume(); soundRef.current = !sound; setSound(!sound); }}>{sound ? '♪ เปิดเสียงแล้ว' : 'เปิดเสียงออเดอร์ใหม่'}</button><button onClick={async () => { await api.logout(identity); setIdentity(null); setState(emptyState); }}>ออกจากระบบ</button></div></header><nav className="staff-nav" aria-label="หน้าจอร้าน">{tabs.filter(([key]) => identity.role === 'owner' || !['menu', 'qr', 'accounts'].includes(key)).map(([key, label]) => <button className={tab === key ? 'active' : ''} aria-current={tab === key ? 'page' : undefined} key={key} onClick={() => { setTab(key); setError(''); }}>{label}{key === 'kitchen' && activeOrders.length > 0 && <span>{activeOrders.length}</span>}</button>)}</nav><main className="staff-container">
    {error && <p className="error-message" role="alert">{error}</p>}<p className="sr-only" aria-live="polite">{notice}</p>
    {tab === 'pos' && <><div className="section-top"><div><p className="eyebrow">รับลูกค้า ดูโต๊ะ คิดเงิน</p><h1>โต๊ะและออเดอร์</h1></div><button className="primary-action" onClick={() => setCompose({ channel: 'takeaway', table: null })}>+ เปิดออเดอร์กลับบ้าน</button></div><div className="table-grid">{Array.from({ length: 8 }, (_, i) => i + 1).map(table => { const visit = state.visits[table]; const orders = state.orders.filter(o => o.visitId === visit?.id && o.tableNumber === table); const due = orders.filter(o => !o.paidAt && o.status !== 'cancelled').reduce((s, o) => s + o.totalSatang, 0); return <button key={table} className={'table-card ' + (visit ? 'occupied' : 'free') + (filter === String(table) ? ' selected' : '')} onClick={() => { setFilter(String(table)); if (!visit) setCompose({ channel: 'dine_in', table }); }}><span>โต๊ะ {table}</span><strong>{visit ? 'เปิดโต๊ะอยู่' : 'โต๊ะว่าง'}</strong><small>{visit ? 'ค้างชำระ ' + money(due) : 'แตะเพื่อเปิดออเดอร์'}</small></button>; })}</div><div className="order-filters"><button className={filter === 'all' ? 'active' : ''} onClick={() => setFilter('all')}>ทั้งหมด</button><button className={filter === 'takeaway' ? 'active' : ''} onClick={() => setFilter('takeaway')}>กลับบ้าน</button>{/^\d+$/.test(filter) && <><span>โต๊ะ {filter}</span><button onClick={() => setCompose({ channel: 'dine_in', table: Number(filter) })}>+ เพิ่มออเดอร์โต๊ะนี้</button>{state.visits[filter] && <button disabled={busy} onClick={() => void closeTable(Number(filter))}>ปิดรอบโต๊ะ</button>}</>}</div><div className="ticket-grid">{[...visibleOrders].sort((a, b) => a.createdAt.localeCompare(b.createdAt)).map(order => <Ticket key={order.id} order={order} identity={identity} busy={busy} onAction={(...args) => void action(...args)} />)}</div>{!visibleOrders.length && <div className="empty-state"><span aria-hidden="true">🍜</span><h2>ยังไม่มีออเดอร์ในกลุ่มนี้</h2><p>ออเดอร์จากลูกค้าจะแสดงที่นี่</p></div>}</>}
    {tab === 'kitchen' && <><div className="section-top"><div><p className="eyebrow">ทำตามคิว ส่งมอบให้ครบ</p><h1>ห้องครัว <span className="count-pill">{activeOrders.length}</span></h1></div><button onClick={() => void refresh()}>↻ โหลดใหม่</button></div><div className="kitchen-columns">{(['new', 'preparing', 'ready'] as Status[]).map(status => <section key={status}><h2>{statusNames[status]} <span>{activeOrders.filter(o => o.status === status).length}</span></h2>{activeOrders.filter(o => o.status === status).map(order => <Ticket key={order.id} order={order} identity={identity} busy={busy} onAction={(...args) => void action(...args)} />)}{!activeOrders.some(o => o.status === status) && <p className="column-empty">ไม่มีรายการ</p>}</section>)}</div></>}
    {tab === 'dashboard' && <Dashboard identity={identity} />}
    {tab === 'delivery' && <Delivery identity={identity} summaries={state.summaries} refresh={() => refresh()} />}
    {tab === 'menu' && <MenuEditor catalog={catalog} identity={identity} refresh={refreshMenu} />}
    {tab === 'qr' && <QrCards identity={identity} />}
    {tab === 'accounts' && <Accounts identity={identity} />}
  </main></div>;
}
function Delivery({ identity, summaries, refresh }: { identity: Identity; summaries: DeliverySummary[]; refresh: () => Promise<void> }) {
  const [date, setDate] = useState(businessDate()); const [channel, setChannel] = useState<'grabfood' | 'lineman'>('grabfood'); const [gross, setGross] = useState(''); const [discount, setDiscount] = useState('0'); const [refund, setRefund] = useState('0'); const [count, setCount] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  async function save(values: DeliverySummary[]) { if (values.some(v => summaries.some(s => s.date === v.date && s.channel === v.channel)) && !confirm('มีข้อมูลช่องทางและวันที่นี้อยู่แล้ว ต้องการใช้ยอดใหม่แทนยอดเดิมใช่ไหม?')) return; setBusy(true); try { values.forEach(validateSummary); await api.delivery(identity, values); await refresh(); setMessage('บันทึกยอดแล้ว ไม่มีการบวกซ้ำสำหรับช่องทางและวันเดิม'); } catch (e) { setMessage((e as Error).message); } finally { setBusy(false); } }
  async function importCsv(file: File) { try { const lines = (await file.text()).replace(/^\uFEFF/, '').trim().split(/\r?\n/); if (lines[0] !== 'date,channel,gross,discount,refund,order_count') throw new Error('หัว CSV ต้องเป็น date,channel,gross,discount,refund,order_count'); const values = lines.slice(1).filter(Boolean).map(line => { const cells = line.split(','); if (cells.length !== 6) throw new Error('CSV ต้องมี 6 คอลัมน์ และใช้ตัวเลขไม่คั่นหลักพัน'); return { date: cells[0], channel: cells[1] as DeliverySummary['channel'], grossSatang: parseBaht(cells[2]), discountSatang: parseBaht(cells[3]), refundSatang: parseBaht(cells[4]), orderCount: cells[5] === '' ? null : /^\d+$/.test(cells[5]) ? Number(cells[5]) : NaN }; }); await save(values); } catch (e) { setMessage((e as Error).message); } }
  return <section><p className="eyebrow">เริ่มจากยอดสรุปที่ตรวจได้</p><h1>ยอด Delivery</h1><p className="muted">บันทึกยอดขายก่อนหักค่าธรรมเนียม ไม่ใช่ยอดโอนเข้าบัญชี</p>{identity.role === 'owner' && <form className="panel delivery-form" onSubmit={e => { e.preventDefault(); try { void save([{ date, channel, grossSatang: parseBaht(gross), discountSatang: parseBaht(discount), refundSatang: parseBaht(refund), orderCount: count === '' ? null : /^\d+$/.test(count) ? Number(count) : NaN }]); } catch (error) { setMessage((error as Error).message); } }}><div className="form-grid"><label>วันที่<input type="date" value={date} onChange={e => setDate(e.target.value)} required /></label><label>ช่องทาง<select value={channel} onChange={e => setChannel(e.target.value as typeof channel)}><option value="grabfood">GrabFood</option><option value="lineman">LINE MAN</option></select></label><label>ยอดก่อนส่วนลด (บาท)<input inputMode="decimal" value={gross} onChange={e => setGross(e.target.value)} required /></label><label>ส่วนลด (บาท)<input inputMode="decimal" value={discount} onChange={e => setDiscount(e.target.value)} required /></label><label>คืนเงิน (บาท)<input inputMode="decimal" value={refund} onChange={e => setRefund(e.target.value)} required /></label><label>จำนวนออเดอร์<input inputMode="numeric" value={count} onChange={e => setCount(e.target.value)} placeholder="เว้นว่างหากไม่ทราบ" /></label></div><button className="primary-action" disabled={busy}>บันทึกยอดรายวัน</button><div className="csv-import"><label>หรือนำเข้า CSV<input type="file" accept=".csv,text/csv" disabled={busy} onChange={e => { const file = e.target.files?.[0]; if (file) void importCsv(file); e.target.value = ''; }} /></label><a href="/delivery-template.csv" download>ดาวน์โหลดตัวอย่าง CSV</a></div></form>}{message && <p className="info-message" role="status">{message}</p>}<div className="panel table-overflow"><table><thead><tr><th>วันที่</th><th>ช่องทาง</th><th>ยอดสุทธิ</th><th>ออเดอร์</th></tr></thead><tbody>{[...summaries].sort((a, b) => b.date.localeCompare(a.date)).map(s => <tr key={s.date + s.channel}><td>{s.date}</td><td>{channelNames[s.channel]}</td><td>{money(s.grossSatang - s.discountSatang - s.refundSatang)}</td><td>{s.orderCount ?? 'ไม่ทราบ'}</td></tr>)}</tbody></table>{!summaries.length && <p className="muted">ยังไม่มีข้อมูล Delivery</p>}</div></section>;
}
function MenuEditor({ catalog, identity, refresh }: { catalog: MenuItem[]; identity: Identity; refresh: () => Promise<MenuItem[]> }) {
  const [selected, setSelected] = useState<MenuItem | null>(null); const [prices, setPrices] = useState<Record<string, string>>({}); const [available, setAvailable] = useState(true); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  return <section><p className="eyebrow">ตรวจราคาและความพร้อมขาย</p><h1>จัดการเมนู</h1><p className="info-message">เมนูตั้งต้น {catalog.length} รายการ กรุณาตรวจชื่อ ราคา และตัวเลือกก่อนใช้รับออเดอร์จริง รูปอาหารยังปิดอยู่ทั้งหมด</p>{message && <p role="status">{message}</p>}{selected ? <form className="panel" onSubmit={async e => { e.preventDefault(); setBusy(true); try { const values = Object.fromEntries(Object.entries(prices).map(([code, value]) => [code, parseBaht(value)])); await api.editMenu(identity, selected.code, values, available); await refresh(); setSelected(null); setMessage('บันทึกเมนูแล้ว ออเดอร์เก่าใช้ราคาเดิม'); } catch (error) { setMessage((error as Error).message); } finally { setBusy(false); } }}><h2>{selected.name}</h2>{selected.variants.map(v => <label key={v.code}>ราคา{v.name} (บาท)<input inputMode="decimal" value={prices[v.code]} onChange={e => setPrices(p => ({ ...p, [v.code]: e.target.value }))} required /></label>)}<label className="inline-check"><input type="checkbox" checked={available} onChange={e => setAvailable(e.target.checked)} />เปิดขายเมนูนี้</label><div className="form-actions"><button type="submit" className="primary-action" disabled={busy}>บันทึกเมนู</button><button type="button" onClick={() => setSelected(null)}>กลับ</button></div></form> : <div className="inventory-list">{catalog.map(item => <article className="panel inventory-row" key={item.code}><span aria-hidden="true">🍜</span><div><h2>{item.name}</h2><p>{item.variants.map(v => v.name + ' ' + money(v.priceSatang)).join(' / ')}</p><span className={item.available ? 'available' : 'danger-text'}>{item.available ? 'พร้อมขาย' : 'ปิดขายชั่วคราว'}</span></div><button onClick={() => { setSelected(item); setAvailable(item.available); setPrices(Object.fromEntries(item.variants.map(v => [v.code, String(v.priceSatang / 100)]))); setMessage(''); }}>แก้ไข</button></article>)}</div>}</section>;
}
function QrCards({ identity }: { identity: Identity }) {
  const [codes, setCodes] = useState<{ label: string; url: string; image: string }[]>([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function generate() { if (mode === 'supabase' && !confirm('สร้าง QR ใหม่จะทำให้ QR เดิมใช้ไม่ได้ ต้องการสร้างใหม่ใช่ไหม?')) return; setBusy(true); try { const entries = await api.qr(identity); const result = await Promise.all(entries.map(async entry => ({ ...entry, image: await QRCode.toDataURL(entry.url, { width: 360, margin: 3, errorCorrectionLevel: 'M' }) }))); setCodes(result); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <section><p className="eyebrow">ให้ลูกค้าเริ่มจากโต๊ะของตัวเอง</p><h1>QR ประจำโต๊ะ</h1><p className="muted">{mode === 'demo' ? 'QR ทดลองใช้ URL ของเครื่องนี้ ยังไม่ใช่ QR สำหรับสแกนจากมือถือคนละเครื่อง' : 'ดาวน์โหลดและเก็บ QR ชุดนี้ไว้ การสร้างใหม่จะเปลี่ยน token ชุดเดิม'}</p><button className="primary-action" disabled={busy} onClick={() => void generate()}>{busy ? 'กำลังสร้าง…' : 'สร้าง QR โต๊ะ 1–8 และกลับบ้าน'}</button>{error && <p role="alert" className="error-message">{error}</p>}<div className="qr-grid">{codes.map(code => <article className="panel" key={code.label}><h2>{code.label}</h2><img src={code.image} width="240" height="240" alt={'QR สำหรับ ' + code.label} /><a className="link-button" href={code.url} target="_blank" rel="noreferrer">เปิดหน้าสั่งอาหาร</a><a href={code.image} download={'prod-qr-' + code.label + '.png'}>ดาวน์โหลด QR</a></article>)}</div></section>;
}
function Accounts({ identity }: { identity: Identity }) {
  const [accounts, setAccounts] = useState<{ id: string; name: string; role: string; active: boolean; slot: number }[]>([]); const [error, setError] = useState('');
  useEffect(() => { void api.accounts(identity).then(setAccounts).catch(e => setError(e.message)); }, [identity.id]);
  return <section><p className="eyebrow">บัญชีร้านทั้งหมด 4 ช่อง</p><h1>บัญชีพนักงาน</h1><p className="info-message">{mode === 'demo' ? 'บัญชีทดลองใช้รหัส 1234 เหมือนกัน ใช้เฉพาะโหมดบนเครื่อง บัญชีจริงต้องสร้างใน Supabase Auth' : 'ข้อมูลบัญชีอ่านจาก Supabase Auth profile การตั้งรหัสผ่านใช้หน้าจัดการ Auth ของเจ้าของโปรเจกต์'}</p>{error && <p role="alert">{error}</p>}<div className="account-grid">{accounts.map(account => <article className="panel" key={account.id}><span className="account-number">0{account.slot}</span><h2>{account.name}</h2><p>{account.role === 'owner' ? 'เจ้าของร้าน' : 'พนักงาน'}</p><span className="status-badge">{account.active ? 'เปิดใช้งาน' : 'ปิดใช้งาน'}</span></article>)}</div></section>;
}
